name: Main
on:
  release:
    types:
      - published
jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.platform }}
    steps: 
      - uses: actions/checkout@v3
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        id: setup_node_id
        with:
          node-version: 15.x
          cache: npm
      - name: Install Packages
        if: ${{ steps.setup_node_id.outputs.cache-hit != 'true' }}
        run: npm install
      - name: Build MacOS
        if: ${{ matrix.platform == 'macos-latest' }}
        run: npm run build:mac
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      - name: Build Windows
        if: ${{ matrix.platform == 'windows-latest' }}
        run: |
          npm run build
          npm run build:portable
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      - name: Build Linux
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/Monot-*.dmg
            dist/*.exe
            dist/*.zip
            dist/Monot-*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
